### ISSUE TITLE
IQ is swapped

### ISSUE THREAD

**Issue by Sec42** [rad1o/hackrf#6]
During normal use, i and q are swapped resulting in frequencies being inverted.

**Comment by schneider42** [comment]
Which is strange, as everything related to this data path should be identical to the HackRF.

I've observed it too and simply inverting all calls to `sgpio_cpld_stream_rx_set_q_invert` "solves" the problem.

**Comment by schneider42** [comment]
We have a completely different IQ polarity that he hackrf. Has been fixed in firmware.
