### ISSUE TITLE
rad1o only works when rx amp is enabled

### ISSUE THREAD

**Issue by Sec42** [rad1o/hackrf#7]
someone needs to debug this :)

**Comment by schneider42** [comment]
I have not yet been able to figure this one out. I've tried to check if the correct code sections are executed and they are. I'm also pretty sure that we did test this with the feldtest application on the prototypes.

**Comment by schneider42** [comment]
I've just checked the `BY_AMP` and `BY_AMP_N` signals and they are as expected. The circuit is pretty straight forward too. I can't say why it is not working.

**Comment by schneider42** [comment]
Has been fixed a while ago.
